SET NAMES utf8mb4;
USE daelim;

CREATE TABLE IF NOT EXISTS MENU (
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME    VARCHAR(50)  NOT NULL,
    CATEGORY     VARCHAR(20)  NOT NULL,
    PRICE        INT          NOT NULL,
    RELEASE_DATE DATE         NOT NULL
) ENGINE=InnoDB CHARACTER SET=utf8mb4;

INSERT INTO MENU (MENU_NAME, CATEGORY, PRICE, RELEASE_DATE) VALUES
('아메리카노', '커피', 4500, '2024-01-01');
